import React from "react";
import {
  Image,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

const T = {
  leaf: "#22543d",
  leafMid: "#276749",
  sagePale: "#d4edda",
  inkDark: "#1a202c",
  inkMid: "#2d3748",
  inkLight: "#718096",
  border: "#e2e8f0",
  borderGreen: "#9ae6b4",
  white: "#ffffff",
  bg: "#f1f8e9",
  cream: "#faf7f0",
  amber: "#c8860a",
  amberPale: "#fef9e7",
};

// ── Static herb data (swap with API response later) ───────────────────────────
const HERB = {
  englishName: "Bitter Gourd",
  sinhalaName: "කරවිල",
  image: {
    uri: "https://i1.wp.com/nourhealth.sg/wp-content/uploads/2017/10/Bitter-gourd-bitter-melon-slices.jpg?fit=1800%2C1200&ssl=1",
  },
  howToUse: [
    { step: "1", text: "Wash and slice 2–3 fresh bitter gourd pieces." },
    { step: "2", text: "Boil in 2 cups of water for 10 minutes." },
    {
      step: "3",
      text: "Strain and drink as a warm tea or consume the slices directly.",
    },
  ],
  whenToUse: "before" as "before" | "after",
  mealTip: "Take 30 minutes before meals on an empty stomach for best results.",
  dosage: "100 ml decoction, twice daily",
  benefit:
    "Balances blood sugar, reduces Pitta, supports digestion and liver function.",
};

interface HerbResultsProps {
  onBack: () => void;
  onRestart: () => void;
}

export default function HerbResults({ onBack, onRestart }: HerbResultsProps) {
  const isBefore = HERB.whenToUse === "before";

  return (
    <ScrollView
      style={styles.screen}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
    >
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerIconRing}>
          <Text style={styles.headerEmoji}>🌿</Text>
        </View>
        <Text style={styles.headerTitle}>Recommended Herb</Text>
        <Text style={styles.headerSub}>
          Based on your dosha profile, agni state, and symptom assessment
        </Text>
      </View>

      {/* ── Main Herb Card ── */}
      <View style={styles.card}>
        <View style={styles.cardStripe} />

        {/* Image */}
        <Image
          source={HERB.image}
          style={styles.herbImage}
          resizeMode="cover"
        />

        {/* Name block */}
        <View style={styles.nameBlock}>
          <Text style={styles.sinhalaName}>{HERB.sinhalaName}</Text>
          <Text style={styles.englishName}>{HERB.englishName}</Text>
          <View style={styles.benefitBox}>
            <Text style={styles.benefitText}>{HERB.benefit}</Text>
          </View>
        </View>

        <View style={styles.divider} />

        {/* When to use */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>⏰ When to Use</Text>
          <View
            style={[
              styles.whenBadge,
              {
                backgroundColor: isBefore ? T.sagePale : T.amberPale,
                borderColor: isBefore ? T.borderGreen : "#f6d860",
              },
            ]}
          >
            <Text
              style={[
                styles.whenBadgeText,
                { color: isBefore ? T.leaf : T.amber },
              ]}
            >
              {isBefore ? "🍽️  Before Meals" : "🍽️  After Meals"}
            </Text>
          </View>
          <Text style={styles.mealTip}>{HERB.mealTip}</Text>
        </View>

        <View style={styles.divider} />

        {/* How to use */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>📖 How to Use</Text>
          {HERB.howToUse.map((item) => (
            <View key={item.step} style={styles.stepRow}>
              <View style={styles.stepCircle}>
                <Text style={styles.stepNum}>{item.step}</Text>
              </View>
              <Text style={styles.stepText}>{item.text}</Text>
            </View>
          ))}
        </View>

        <View style={styles.divider} />

        {/* Dosage */}
        <View style={styles.dosageRow}>
          <Text style={styles.dosageIcon}>💊</Text>
          <View>
            <Text style={styles.dosageLabel}>Recommended Dosage</Text>
            <Text style={styles.dosageValue}>{HERB.dosage}</Text>
          </View>
        </View>
      </View>

      {/* Disclaimer */}
      <View style={styles.disclaimer}>
        <Text style={styles.disclaimerIcon}>⚕️</Text>
        <Text style={styles.disclaimerText}>
          This recommendation is generated by an AI model trained on Ayurvedic
          data. Always consult a qualified Ayurvedic physician before starting
          any herbal treatment.
        </Text>
      </View>

      {/* Navigation */}
      <View style={styles.navRow}>
        <TouchableOpacity
          onPress={onBack}
          activeOpacity={0.8}
          style={styles.backBtn}
        >
          <Text style={styles.backBtnText}>← Back</Text>
        </TouchableOpacity>
        <TouchableOpacity
          onPress={onRestart}
          activeOpacity={0.85}
          style={styles.restartBtn}
        >
          <Text style={styles.restartBtnText}>🔄 New Assessment</Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  content: { padding: 20, paddingBottom: 48 },

  header: { alignItems: "center", marginBottom: 20 },
  headerIconRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: T.white,
    borderWidth: 2,
    borderColor: T.borderGreen,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    shadowColor: T.leaf,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  headerEmoji: { fontSize: 34 },
  headerTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: T.inkDark,
    letterSpacing: 0.3,
    textAlign: "center",
    marginBottom: 6,
  },
  headerSub: {
    fontSize: 13,
    color: T.inkLight,
    textAlign: "center",
    lineHeight: 19,
    paddingHorizontal: 16,
  },

  card: {
    backgroundColor: T.white,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: T.borderGreen,
    marginBottom: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  cardStripe: { height: 5, backgroundColor: T.leaf },
  herbImage: { width: "100%", height: 200 },

  nameBlock: { padding: 20, paddingBottom: 16 },
  sinhalaName: {
    fontSize: 32,
    fontWeight: "800",
    color: T.leaf,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  englishName: {
    fontSize: 16,
    fontWeight: "600",
    color: T.inkMid,
    marginBottom: 12,
    letterSpacing: 0.2,
  },
  benefitBox: {
    backgroundColor: T.sagePale,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: T.borderGreen,
  },
  benefitText: { fontSize: 13, color: T.leafMid, lineHeight: 20 },

  divider: { height: 1, backgroundColor: T.border, marginHorizontal: 20 },

  section: { padding: 20 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: T.inkDark,
    marginBottom: 12,
    letterSpacing: 0.2,
  },

  whenBadge: {
    alignSelf: "flex-start",
    borderRadius: 20,
    borderWidth: 1.5,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 10,
  },
  whenBadgeText: { fontSize: 14, fontWeight: "700" },
  mealTip: { fontSize: 13, color: T.inkMid, lineHeight: 20 },

  stepRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 14,
    alignItems: "flex-start",
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: T.leaf,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  stepNum: { color: T.white, fontSize: 12, fontWeight: "800" },
  stepText: { flex: 1, fontSize: 13, color: T.inkMid, lineHeight: 20 },

  dosageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 20,
    paddingTop: 16,
  },
  dosageIcon: { fontSize: 22 },
  dosageLabel: {
    fontSize: 12,
    color: T.inkLight,
    fontWeight: "600",
    marginBottom: 3,
  },
  dosageValue: { fontSize: 14, fontWeight: "700", color: T.inkDark },

  disclaimer: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: T.cream,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: T.border,
    padding: 14,
    marginBottom: 20,
  },
  disclaimerIcon: { fontSize: 16, marginTop: 1 },
  disclaimerText: { flex: 1, fontSize: 12, color: T.inkLight, lineHeight: 18 },

  navRow: { flexDirection: "row", gap: 10 },
  backBtn: {
    flex: 1,
    backgroundColor: T.sagePale,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: T.borderGreen,
  },
  backBtnText: { color: T.leaf, fontWeight: "700", fontSize: 15 },
  restartBtn: {
    flex: 2,
    backgroundColor: T.leaf,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
    shadowColor: T.leaf,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  restartBtnText: { color: T.white, fontWeight: "700", fontSize: 15 },
});
